apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: # Hiermit werden alle EdgeNodes selektiert
      automountServiceAccountToken: false
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      tolerations: # Mit dieser Toleration wird das Taint ignoriert
      - effect: NoSchedule
        key: node-role.kubeedge.io
        value: edge
      containers:
      - name: nginx
        image: nginx:1.15.12
        ports:
        - containerPort: 8080
          hostPort: 8080