apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-temp-client
  labels:
    app: cpu-temp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-temp-client
  template:
    metadata:
      labels:
        app: cpu-temp-client
    spec:
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      tolerations: # Mit dieser Toleration wird das Taint ignoriert
      - effect: NoSchedule
        key: node-role.kubeedge.io
        value: edged
      containers:
      - name: cpu-temp-client
        image: theringli/cpu-temp-client:latest
        args:
          - "--mqttURL=tcp://192.168.178.114:1883"
          - "--deviceID=cpu-sensor-tag01"
          - "--simulate=true"
          # - "--user="
          # - "--password="
