---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeedge-database

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeedge-database
  labels:
    k8s-app: kubeedge
    kubeedge: kubeedge-database
rules:
- apiGroups:
  - "devices.kubeedge.io"
  resources:
  - devices
  - devicemodels
  verbs:
  - watch
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeedge-database
  labels:
    k8s-app: kubeedge
    kubeedge: kubeedge-database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeedge-database
subjects:
- kind: ServiceAccount
  name: kubeedge-database
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: kubeedge-database-database
type: Opaque
stringData:
  user: kubeedge
  password: kubeedge

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge
    kubeedge: kubeedge-database
  name: kubeedge-database
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: kubeedge-database
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: kubeedge-database
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      initContainers:
      - name: kubeconfig
        image: alpine:3.10
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/kubeedge-database/conf
            subPath: kubeconfig.yaml
            name: kubeconfig
        command:
          - /bin/sh
          - -c
          - |
            tee /etc/kubeedge-database/conf/kubeconfig.yaml <<EOF
            apiVersion: v1
            clusters:
            - cluster:
                certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EZ3dPVEUxTkRVek4xb1hEVE14TURnd056RTFORFV6TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHpqCmI4ejE3bC83bTc2NXVzOEZadHZHbkNkNzJrN3JsUllhUEtyNHBCaW5aYlpvV2IwSmhLdmpDVkVqT2tQN3hVdXcKNytnUzdEQ0JZME1VOHg4VEJvOXJWTFhST2dmOXFvdGMwMWFyRk1TYlhuekkxRkJ3Vyt3UGwyTGs0UktYQ2VpTQpCWnlscG1SdVpVTjZqV1djMmphREROemc5bE0vNC85d3RkUktEdU5qb3FmejJhQWZHeEp3c3kyZ1FQNlpPc2dhCmloakNwWWFqa0JjTm9ad0RpYklnUWVZbTJURDA2M2VZTGkxSVdyZ0hZSFNzSmFzZEU4dUhYZmFOTXBYbEhldnAKSWFueFQ5enlQckJHSDJGbnpRMWdneHQ3YmdTSHR2Wjk3b2pHdkZBYyt2NERDM0dUTkVRUlB6RStoVWFHSnRENAp5SkpaSUszNS94YVVqald5ei9zQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDL3BxQThoZDVCZk9wRFhXcmkzQk1XVytVWFJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDcG5vQUlmNy9rVVVqYVFNZTV3L3l0Q3lQMERHRjNnMitMWWdjMHBBUHVRTUxPWEN1cworZlMwL0piMjNEeERNNklCSHZ2MHpBRUViWFA1OE9FMHJRc1lvSGZ1amZuV01NcXBTVm1HOFhCWE5ENU5uMEU3CmpYTGpCZERNSjhsWlhGQjVHZ1preGc1cWNmWTVKZjhIS1k3anowdDZpa1N0ODNzOXhRamVmTURiSGNzcWFjcjAKb0RaaVR1N1FHMVBDRU9ORDRya2dyNWcyNmJORm0xRTBDbHZqa29nblRVeUJtd3A1OXdaRm1rSFoybEthUU9sSAphSUtWNE1HM2VhNlRRRFZuVjRrQjg0SDVaVm5VS1lRS1pTWk9VWXIwR2VoZmVWNTMzd2hPdlNZQnpNc0RkQ0o2CjBEWDJ5UWc3bGhqVjhaOGhkeW9EVmNnUnRhUmZ4aU9ZbkwzVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
                server: https://192.168.178.112:6443
              name: kubernetes
            contexts:
            - context:
                cluster: kubernetes
                user: kubernetes-admin
              name: kubernetes-admin@kubernetes
            current-context: kubernetes-admin@kubernetes
            kind: Config
            preferences: {}
            users:
            - name: kubernetes-admin
              user:
                client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJTEFmcVFuUnViTFV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRBNE1Ea3hOVFExTXpkYUZ3MHlNakE0TURreE5UUTFNemxhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNURE5sbm92SndyNVVyRFQKbXJQTi9Bd1Y5L0dkV3lSQ1FnTW9YSmNZOW5pSzZRSDJrcXNlbjhsQ3pac2wvTTcrd3JmdEIyUUpHOEFJWWJmSApGV05YSjFLeEhIMHZDT25uUEF0dFVOOXlLbzZDbTJ0M0dzU2xidFFiMldKaVZlandrNjFQL0xXMlkyT2wvRU4yCnNXa2ZPMml4aWF4NURBdlB0elU0aXNycTFIS2JPcURldE11ZUcyMisyZmNHSmovZ0NiRHNmcEFyZ2VDRjVIK1IKemcyRTJFQlcxSzl4VE5LWU9MZEh4a3JrL0pkMEJGblg4T2hRV0RSNjN6Tmp3QmFqS292QjYyaXlxdjZoMzdPNgptRlhSSlpuT1A5K3ZXeS91Q25vVElNNUY2RnhqQngvZ2Y3amVMVlZWUFZNQlllUWhMY3JPbUhlSSs3dFNLNGdWCll6WUhJUUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JRdjZhZ1BJWGVRWHpxUTExcTR0d1RGbHZsRgowVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbC9GczV6anlGUGdFMngyLzRWZVZ3dEdpWXFwZEsvNU9HaUNMCjRqZW5vcHpPRmlQZUI4REdKWG1YTW8yNGQzQk80MzR0RU5EWXVtdy81ajZWYjdVNHhKZERxVzEvTFU4RjF6QncKQmlQYUZnK0xqZlpSUFZtdWRVYmhJbGluSG1wS2JuYlErOUVydGEvbmZlaUNWLzZtQWM1V3ZkZEpQQVVjSUFiagpmRFFXWHdSUHNWZmVZcWZva0dhY0I0STdzVkswY1lTN3JXSnhRU1lUOHc4WTFlWWtBRWFNT0JTS01HS21CYkdTClQ0RlZLWFJwbFArdmd2NUR2di81S1dScWRTaVpOZjdhTWhzanpteEZtSXZRSWdWUE1aWXEvWFJWOTI2N3YxcS8KMGtiajNCOTBHcUtKdHJsWXUyaERrQVI4d3hYSGZyN1VpOHpEelVWZnExbENKMjhrTFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
                client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBM1RETmxub3ZKd3I1VXJEVG1yUE4vQXdWOS9HZFd5UkNRZ01vWEpjWTluaUs2UUgyCmtxc2VuOGxDelpzbC9NNyt3cmZ0QjJRSkc4QUlZYmZIRldOWEoxS3hISDB2Q09ublBBdHRVTjl5S282Q20ydDMKR3NTbGJ0UWIyV0ppVmVqd2s2MVAvTFcyWTJPbC9FTjJzV2tmTzJpeGlheDVEQXZQdHpVNGlzcnExSEtiT3FEZQp0TXVlRzIyKzJmY0dKai9nQ2JEc2ZwQXJnZUNGNUgrUnpnMkUyRUJXMUs5eFROS1lPTGRIeGtyay9KZDBCRm5YCjhPaFFXRFI2M3pOandCYWpLb3ZCNjJpeXF2NmgzN082bUZYUkpabk9QOSt2V3kvdUNub1RJTTVGNkZ4akJ4L2cKZjdqZUxWVlZQVk1CWWVRaExjck9tSGVJKzd0U0s0Z1ZZellISVFJREFRQUJBb0lCQVFEUzdWY2Z5Q1J1OXVnTApFdFMzRWYrNyswcDN4dEJudVl2MXAwMDEvbUN2cVFQT2J6RFRiSnNuaEtWUHJFUHRjUGRBZUdSd1I5VG53Wmc4Cmx5UWlJVGxiSmwvKzZ1R1BmbjRqcEVINmZScEJ1dVNSa1VsakhXTWs3T0Foek5BNVhJa09TcGVjUlN4SVd4NU8KRVlkK1p1Q0JwclNtdFBJNXFvbktDOVovaEVHcmxGZ21DQngrVXZPdkJtcFRMLzI3TFpTUGczTzRxYVlySXBXQQpEL2FNdUtOQmt1empSblhUL1phMEJuaGgxc1NHMDVJTTZOR2hqcjdYYmpETk9sUngxN3BOaGdZeTFnTmdEdVV0CnMxN01QbFlneXd3MmpIVUVpbUhadUpLQk9QNUJOM1F5OVRiM1ZPc2ZQVVZmQUgzL0dYbE9RMXpZazBGa1JmVHIKa3NkWXRRQ0JBb0dCQVB1ZlFkeW9pWVpFckxQczF0TDdqczhVMVRldnU0SDlEOTdqTjR4SW5sa0dxMHpRdUJiZQpRbnBjdGcxWTRCSFlsWnAyTmY5eEdzV1dGYjREU0VSYnFEM3NmSzFUZWwzclhxNWhtQ0JqY2o4REJaTUphRkdnCldXdURNNUlHdE9jWGd4Nno1REFrdWd5bkIwR0tFUFN5dWFXSzBvOFFocElXczRadkNmT0p6dG1YQW9HQkFPRUsKQUgwYkkxaTNNQmhTbXZQd3RUSkRSdXF5cU1GS1VUMVg1ekVOc2haNTdmdkVrenh2N09DMEt2MzNIdWMwcjlLYgpJMVBOcWNGa3ZNbDJKNHM0dTBvMzVaUUlhZGxQdlFlUDFZM2krYmExeHdtRzJUeGRwR2syalgveW1NaGI5NWIrCmhFUkxONUR6VkZtVTBzWkx0ZnZOTVBYaFp6bEJpd2tDbHRRejNRd0hBb0dBWjRwcE43dkNtNVcyMjNNaUV6K2cKekdYdU56UUJITVJkdTRJVVlZMmdXMUg3TzJqSDErRXR5ZHhNcmNGY3N2dEUxSUxBUlpUdFIxRXpNVFY0ajJpSQpHck10dXNVWEhYNjFQMXk1bE5wWE1NYTFqSVBhZ1h4U1Q0TjF2U2sxVjhLOUdlMDhnUE1iL0FqZlc0RE02V1NDCk1EU240R2NVZVJrT1ZzdHFkT1RJVVpFQ2dZQTRtaTl0U0RvbndrdlNrbFJ2THdna1VFK3lFS1hwbUN1KzVqRTgKWVZsOTFjVktJak4yYkNDRWxFeUwvSEJGYnpjYUhmTlF6Tlg1MHNDNVc0S3V2ZUk5MUxsbDlvZkpKUWxDc2FiaApQVW5aN3ZiVktwblJXU3hWV21kVTIwd2FlU2RaVDBNdGVrM0xvNmgvcjdNa05UN2N5c3Vaek13TjFyS0YzYVRhClV3RXlXUUtCZ0Z1YTB3ODNMVnVtc1ZvbkRTa2Z5bVZ3RkduU0p2WW1hYnl6WGtqalNIWEdGUkpLVGJOL3BrcXQKc0Rza1d4OTl6ZWJGYkM0alEvcHN5aXhpSGJPeGxmek1ZZGFJVWt5cWQwdHJFYW1oM3lpY2hIenU3REQ5RTdZRQo4M3ZwckwzaXVDdXp2aEpTdFEzcVMzYmJsRXlqQm1UekdBalRTSnhWWG1wekJ3Q0d2eUkyCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
            EOF
      containers:
      - name: kubeedge-database
        image: subpathdev/kubeedge-database
        imagePullPolicy: Always
        env:
          - name: DATABASE-USER
            valueFrom:
              secretKeyRef:
                key: user
                name: kubeedge-database-database
          - name: DATABASE-PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: kubeedge-database-database
        args:
          - "--config=/etc/kubeedge-database/conf/kubeconfig.yaml"
          - "--database=demo"
          - "--address=timescale.default.svc.cluster.local"
          - "--port=5432"
          - "--sslmode=disable"
          - "--schema=public"
          - "--timescale"
        volumeMounts:
          - mountPath: /etc/kubeedge-database/conf
            name: kubeconfig
            subPath: kubeconfig.yaml
      volumes:
        - name: kubeconfig
          emptyDir: {}
      restartPolicy: Always
      serviceAccount: kubeedge-database
      serviceAccountName: kubeedge-database
