language: go

sudo: required
dist: disco

go:
        - 1.12

before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
        - mkdir -p $HOME/$GOPATH/src/github.com/subpathdev/CpuTempMqttClient
        - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/$GOPATH/src/github.com/subpathdev/CpuTempMqttClient
        - export TRAVIS_BUILD_DIR=$HOME/$GOPATH/src/github.com/subpathdev/CpuTempMqttClient
        - sudo apt-get install build-essential yamllint
        - go get -d github.com/eclipse/paho.mqtt.golang
        - export PATH=$PATH:$HOME/$GOPATH/bin

install: true

jobs:
        include:
                - stage: "Build Test"
                  script: make
                - stage: "Lint"
                  script: make lint
                - stage: "yaml lint"
                  script: make yamllint
